name: Lint and Test
on: [push, pull_request]
jobs:
  lint:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.6
        id: python_setup
        uses: actions/setup-python@v1
        with:
          python-version: "3.6.10"

      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v1
        with:
          submodules: 'recursive'

#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v2
        
      - name: Lint
        id: python_linting
        env:
          INPUT_METASTORE_CREDENTIALS: '${{ secrets.METASTORE_CREDENTIALS }}'
        run: |
          python3 -m pip install -U pip
          python3 -m pip install -r requirements.txt
          python3 -m pip install flake8
          flake8 . --count --config=.flake8 --show-source --statistics
          flake8 tests --count --config=.flake8 --show-source --statistics

      - name: Test
        id: python_test
        env:
          INPUT_METASTORE_CREDENTIALS: '${{ secrets.METASTORE_CREDENTIALS }}'
        run: |
          python3 -m unittest tests/test*
          python3 -m unittest integration/test*
